### ISSUE TITLE
Dates works locally, but not when served with AWS

### ISSUE THREAD

**Issue by smugclimber** [gjtorikian/jekyll-last-modified-at#69]
Using this code in one of my include files
{{ page.last_modified_at | date: '%B %d, %Y' }}
to show the user the last time the article was updated. The jekyll-last-modified-at plugin works like a charm locally and shows the file mod date in my page html. However, when I push it up to the AWS server, the live site marks every article with January 01, 1970.

Any ideas how to remedy this? Think it's a bug or part of my build setup?

Project Specs:
Jekyll 3.8.5
Bundler 1.16.0
Gem 2.6.11
jekyll-last-modified-at 1.1.0

**Comment by EdenKupe** [comment]
I'm facing a similar issue on Platform.sh. Works well locally but all dates are the same on the live site, set to the last time any page was updated.

**Comment by bronzdoc** [comment]
Facing the same issue in Heroku

**Comment by EdenKupe** [comment]
From what I've been told (sorry, I don't remember where), this is not a bug but a change in how Jekyll works. When you build the site now, Jekyll "touches" all files, essentially modifying them. Haven't been able to find a work-around to this so if anyone has one, let us know!

**Comment by lubc** [comment]
In case anyone is interested, here there's a tool to manage outdated articles in Jekyll: https://github.com/marketplace/outdated-article

**Comment by prenetic** [comment]
I reached out to the folks on the Cloudflare Developers Discord server, and a Cloudflare community member reached out and provided this information:

> We checkout the commit (detached head) so there isn't a history. You could get that commits date but not any previous commits date.

**Comment by itay1313** [comment]
Hey, I'm having the same problem as well :) 
Anyone found a workaround for this?

**Comment by selimslab** [comment]
One way is to build locally and deploy _site 

for gh pages

```
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./_site
```

**Comment by bewuethr** [comment]
I believe this happens when you do a shallow clone or checkout, like what the `actions/checkout` action does by default. As this plugin looks at the most recent Git commit, and there is only one, every `last_modified_at` timestamp is going to be equal to that last commit's time.

A workaround, for GitHub Actions, could be to use `depth: 0` to fetch the entire history, but that can be slow.

**Comment by Mohamed3nan** [comment]
try to concatenating `git fetch --unshallow &&` onto the build command

**Comment by VerzatileDev** [comment]
> I believe this happens when you do a shallow clone or checkout, like what the `actions/checkout` action does by default. As this plugin looks at the most recent Git commit, and there is only one, every `last_modified_at` timestamp is going to be equal to that last commit's time.
> 
> A workaround, for GitHub Actions, could be to use `fetch-depth: 0` to fetch the entire history, but that can be slow.
> 
> Edit: actually, not too bad... my page has 388 commits, and the repo clocks in at about 193 MB; checkout isn't any slower with `fetch-depth: 0`. I guess it depends on your repo history, but if your diffs are mostly adding new things, I believe there isn't a big difference between shallow and deep clones.

Thank you for the work around, Did not even think of using "fetch-depth" to be quite honest, saved me another hour of headache.

**Comment by omarcostahamido** [comment]
@VerzatileDev @bewuethr 
I reckon you add that line in the `.github/workflows/jekyll.yml` file, correct?
Where exactly do you add it?
is it like this?
```
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```
