### ISSUE TITLE
Date shows locally but not on github pages

### ISSUE THREAD

**Issue by chrisevans9629** [gjtorikian/jekyll-last-modified-at#78]
When I am running locally, I correctly see the date at the bottom of the page, but when I publish it on github pages, it's completely blank:

![image](https://user-images.githubusercontent.com/33850520/81403230-8d971780-90f8-11ea-82df-aeb3c3d81661.png)

my default.html layout:

```html
<div class="col"><p>Last Modified at {{ page.last_modified_at | date: '%-d %B %Y %r' }}</p></div>
```

my config:

```yml
plugins:
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'

```

my gem:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'jekyll', '~> 4.0'

group :jekyll_plugins do
    gem "jekyll-last-modified-at"
  end
```
